# Generated by Django 4.2.14 on 2025-03-04 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_useronlinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long.'), django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[\\w._]+$')]),
        ),
    ]
