services:
  frontend:
    container_name: transcendence_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
  backend:
    container_name: transcendence_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - shared-data:/usr/src/app/shared
    ports:
      - "8000:8000"
    networks:
      - backend-network
    environment:
      - ETHEREUM_NETWORK=http://blockchain_ganache:8545
      - OTHER_ENV_VAR=value  
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      ganache:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  ganache:
    image: trufflesuite/ganache:v7.0.0
    container_name: blockchain_ganache
    restart: always
    command: ["-p", "8545", "-m", "myth like bonus scare over problem client lizard pioneer submit female collect"]
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/ganache
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "echo", "Ganache is running"]
      interval: 10s
      retries: 3

  truffle:
    container_name: blockchain_truffle
    build:
      context: ./truffle
      dockerfile: Dockerfile
    volumes:
      - ./truffle:/usr/src/app
      - shared-data:/usr/src/app/shared
    depends_on:
      ganache:
        condition: service_healthy 
    command: ["sh", "/usr/src/app/entrypoint.sh"]
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "ls", "/usr/src/app/shared/deployedAddress.json"]
      interval: 10s
      retries: 3
    
  db:
    container_name: transcendence_db
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  cache:
    image: redis:6
    container_name: transcendence_cache
    expose:
      - 6379
    networks:
      - backend-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - cache_data:/data
    restart: unless-stopped

  waf:
    container_name: modecurity_waf
    build:
      context: ./modsecurity_waf
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8081" # WAF exposed to the client
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  cache_data:
    driver: local
  ganache_data:
    driver: local
  shared-data:
    driver: local

