# Generated by Django 4.2.14 on 2025-01-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_customuser_managers'),
        ('user', '0022_alter_customuser_managers_and_more'),
    ]

    operations = [
    ]
