# Generated by Django 4.2.14 on 2025-01-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_merge_20250120_2226'),
        ('user', '0024_useronlinestatus'),
    ]

    operations = [
    ]
