global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["backend:8000"]
  - job_name: "cache"
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: "db"
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'vault'
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['hashicorpvault:8200']

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager:9093']
