# Generated by Django 4.2.14 on 2025-02-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
