# Generated by Django 4.2.14 on 2025-02-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('games', '0002_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
    ]
