# Generated by Django 4.2.14 on 2025-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_ponggame_player1_alter_ponggame_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='registrado_blockchain',
            field=models.BooleanField(default=False),
        ),
    ]
