# Generated by Django 4.2.14 on 2025-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_ponggame_player1_alter_ponggame_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='registered_on_blockchain',
            field=models.BooleanField(default=False),
        ),
    ]
