# Generated by Django 4.2.14 on 2025-03-14 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_ponggame_registered_on_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='match_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
