# Generated by Django 4.2.14 on 2025-03-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_ponggame_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggame',
            name='match_date',
        ),
    ]
