# Generated by Django 4.2.14 on 2025-02-06 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_delete_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participants_amount', models.IntegerField(choices=[(4, '4')])),
                ('final_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_game', to='games.ponggame')),
                ('participants', models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL)),
                ('semifinal_1_game1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_1_game1', to='games.ponggame')),
                ('semifinal_1_game2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_1_game2', to='games.ponggame')),
                ('semifinal_2_game1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_2_game1', to='games.ponggame')),
                ('semifinal_2_game2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_2_game2', to='games.ponggame')),
            ],
        ),
    ]
