# Generated by Django 4.2.14 on 2025-02-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='semifinal_1_game1',
            new_name='semifinal_1_game',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='semifinal_2_game1',
            new_name='semifinal_2_game',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='semifinal_1_game2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='semifinal_2_game2',
        ),
    ]
