# Generated by Django 4.2.14 on 2025-02-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_ponggame_player1_alter_ponggame_player2'),
        ('tournaments', '0003_rename_semifinal_1_game1_tournament_semifinal_1_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_1_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_1_game', to='games.ponggame'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_2_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_2_game', to='games.ponggame'),
        ),
    ]
